#pragma once


#define IDS_GAME_VERSION_FILE       1
#define IDS_GAME_VERSION_SIZE       2

#define IDM_FILE_LOAD               40001
#define IDM_FILE_SAVE               40002
#define IDM_FILE_ABOUT              40003
#define IDM_FILE_EXIT               40004
#define IDM_OPTIONS_ACCEL           40023
#define IDM_OPTIONS_MENU_RAW        65535

#define IDC_START_VIDEO_DEVICE      1000
#define IDC_START_VIDEO_MODE        1001
#define IDC_START_FULLSCREEN        1005
#define IDC_START_NO_START_DIALOG   1006
#define IDC_START_TRIPLE_BUFFER     1007
#define IDC_START_USE_PALETTE       1008
#define IDC_START_LOW_DETAIL        1009
#define IDC_START_SAVE_DEMO         1010
#define IDC_START_SOUND_HQ          1012
#define IDC_START_BLOOD_PASSWORD    1013
#define IDC_START_BLOOD_DISABLE_TXT 1015
#define IDC_START_BLOOD_ENABLE_TXT  1016
#define IDC_START_BLOOD_MODE        1017

#define IDC_CONNECT_STATUS_TEXT     1010
