#pragma once
#include <cstdint>

namespace as1
{
    enum class ActionCode : std::int32_t
    {
        ACT_ATTACK = 32,
        ACT_MOVE = 33,
        ACT_MOVE_TO = 34,
        ACT_BUILD_UNIT = 35,
        ACT_PATROL = 36,
        ACT_COOR_ATTACK = 37,
        ACT_RANDOM = 38,
        ACT_STOP = 39,
        ACT_PAUSE = 40,
        ACT_ROTATE = 41,
        ACT_CLEAR_COMMAND = 42,
        ACT_FLAGMAN_TRIGGER = 43,
        ACT_PATH_BLOCK = 50,
        ACT_PATH_GROUND = 51,
        ACT_PATH_LIMIT = 52,
        ACT_NO_ITEMS = 53,
        ACT_ADD_ITEM = 54,
        ACT_DELETE_ITEM = 55,
        ACT_HAVE_ITEM = 56,
        ACT_DELETE_ALL_ITEM = 57,
        ACT_GET_ITEM = 58,
        ACT_GET_ITEM_TYPE = 59,
        ACT_CHANGE_DIRECTION = 60,
        ACT_CHANGE_ANIMATION = 61,
        ACT_CHANGE_VID = 62,
        ACT_CHANGE_COOR = 63,
        ACT_BACKUP_COMMAND = 70,
        ACT_GOTO_STACK = 71,
        ACT_CLEAR_STACK = 72,
        ACT_STOP_STACK = 73,
        ACT_RESTORE_COMMAND = 74,
        ACT_COPY_STACK_TO = 75,
        ACT_NO_STACK = 76,
        ACT_WHILE_NOT_SCRIPT_VAR = 79,
        ACT_SAVE = 80,
        ACT_RESTORE = 81,
        ACT_SET_INVULNERABLE = 83,
        ACT_GET_INVULNERABLE = 84,
        ACT_DAMAGE = 85,
        ACT_REPAIR = 86,
        ACT_GET_HP = 87,
        ACT_SET_HP = 88,
        ACT_GET_PERCENT_HP = 89,
        ACT_GET_GOAL = 90,
        ACT_SET_GOAL_COOR = 91,
        ACT_GET_AMMO = 92,
        ACT_ADD_AMMO = 93,
        ACT_GET_BEHAVE = 94,
        ACT_SET_BEHAVE = 95,
        ACT_GET_ARMY = 96,
        ACT_SET_ARMY = 97,
        ACT_SET_INVISIBLE = 98,
        ACT_GET_PARENT = 99,
        ACT_GET_BATTLE_RANGE = 100,
        ACT_GET_LINK = 101,
        ACT_SET_LINK = 102,
        ACT_GET_UPLINK = 103,
        ACT_SET_UPLINK = 104,
        ACT_GET_TIMER = 105,
        ACT_SET_TIMER = 106,
        ACT_GET_ZSPEED = 107,
        ACT_SET_ZSPEED = 108,
        ACT_GET_SPEED = 109,
        ACT_SET_SPEED = 110,
        ACT_GET_COMMAND = 111,
        ACT_SET_DEATH_TIMER = 112,
        ACT_SET_GAMMA = 118,
        ACT_SET_COMMAND = 119,
        ACT_SET_TEXT = 120,
        ACT_GET_TEXT_DESC = 121,
        ACT_SET_TEXT_COUNT = 122,
        ACT_SET_FILE = 123,
        ACT_GET_TEXT = 124,
        ACT_GET_NAME = 125,
        ACT_NEXT_COMMAND = 130,
        ACT_SCRIPT_VAR = 131,
        ACT_UNDO_REMOVE = 132,
        ACT_UNDO_INSERT = 133,
        ACT_DESTROY_UNIT = 134,
        ACT_PLAY_SFX = 135,
        ACT_SET_MAX_SPEED = 138,
        ACT_LINK_ENGINE = 150,
        ACT_CLASH_ENGINE = 151,
        ACT_FORCELINK_ENGINE = 152,
        ACT_TRAIN_BEHAVE = 153,
        ACT_FIRST_ENGINE = 154,
        ACT_LAST_ENGINE = 155,
        ACT_NEXT_ENGINE = 156,
        ACT_IS_FIRST = 157,
        ACT_IN_TRAIN = 158,
        ACT_IS_TRAIN = 159,
        ACT_NONE = 255,
    };

    enum class AnimationCode : std::int32_t
    {
        ANI_STAND = 0,
        ANI_STOP_MOVE = 1,
        ANI_BUILD = 1,
        ANI_GO = 2,
        ANI_START_MOVE = 3,
        ANI_L_ROTATE = 4,
        ANI_R_ROTATE = 5,
        ANI_OPEN = 6,
        ANI_HIT = 7,
        ANI_CLOSE = 7,
        ANI_FIGHT = 8,
        ANI_SALUT = 9,
        ANI_STAND_OPEN = 10,
        ANI_LOAD = 11,
        ANI_CLASH_VERT = 11,
        ANI_LINK = 11,
        ANI_UNLOAD = 12,
        ANI_LAZY = 12,
        ANI_CLASH = 12,
        ANI_WOUND = 13,
        ANI_BIRTH = 14,
        ANI_DEATH = 15,
        ANI_DEATH2 = 16,
        ANI_MENUSTANDDOWN = 0,
        ANI_MENUSTAND = 0,
        ANI_MENUSTANDUP = 1,
        ANI_MENUSELECTDOWN = 2,
        ANI_MENUSELECTUP = 3,
        ANI_MENUPRESSDOWN = 4,
        ANI_MENUPRESSUP = 5,
        ANI_MENUSELECTANIDOWN = 6,
        ANI_MENUSELECTANIUP = 7,
        ANI_MENUDISABLE = 8,
        ANI_MENUDISABLEDOWN = 8,
        ANI_MENUDISABLEUP = 9,
        ANI_FONT_NORMAL = 0,
        ANI_FONT_NEXT_CHAR = 1,
        ANI_FONT_NEXT_LINE = 2,
    };

    enum class SpriteClassCode : std::int32_t
    {
        B_TERRAIN = 0,
        B_OBJECT = 1,
        B_UNIT = 2,
        B_BUILDING = 3,
        B_AVIA = 4,
        B_CANNON = 5,
        B_PRIMITIVE = 6,
        B_MAN = 7,
        B_SPRITE = 9,
        B_FRAME = 10,
        B_BALL = 11,
        B_LINKER = 12,
        B_TEXT = 19,
        B_CIV_ROBOT = 20,
        B_ENGINE = 21,
        B_RAIL = 22,
        B_REGION = 23,
        B_DEPO = 24,
        B_CREATURE = 25,
        B_BALLOON = 26,
        B_MISSILE = 27,
    };

    const char* actionCodeName(std::uint32_t opcode);
    const char* animationCodeName(std::uint32_t opcode);
    const char* spriteClassCodeName(std::uint32_t value);
    bool isActionCode(std::uint32_t opcode);
    bool isAnimationCode(std::uint32_t opcode);
}
